// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: @clsd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.clsd(i64 [[L:%.*]])
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long clsd(long l) {
  return __builtin_kvx_clsd(l);
}

// CHECK-LABEL: @clsw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.clsw(i32 [[I:%.*]])
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int clsw(int i) {
  return __builtin_kvx_clsw(i);
}

// CHECK-LABEL: @errop(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.kvx.errop()
// CHECK-NEXT:    ret void
//
void errop(void) {
  __builtin_kvx_errop();
}
