; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -O2 | FileCheck %s
target triple = "kvx-kalray-cos"

define i1 @test1(i1 returned %a){
; CHECK-LABEL: test1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  ret i1 %a
}

define i16 @test2(i16 %b){
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addw $r0 = $r0, 2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %add = add i16 %b, 2
  ret i16 %add
}

