; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -disable-kvx-hwloops=false -O2 -o - %s | FileCheck %s
target triple = "kvx-kalray-cos"

define void @set(i32* nocapture %x, i32 %num){
; CHECK-LABEL: set:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    cb.weqz $r1 ? .LBB0_2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:  # %bb.1: # %for.body.lr.ph
; CHECK-NEXT:    zxwd $r2 = $r1
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    loopdo $r2, .__LOOPDO_0_END_
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .LBB0_3: # %for.body
; CHECK-NEXT:    # =>This Loop Header: Depth=1
; CHECK-NEXT:    # Child Loop BB0_4 Depth 2
; CHECK-NEXT:    sw 0[$r12] = $r1
; CHECK-NEXT:    make $r2 = 4
; CHECK-NEXT:    addw $r1 = $r1, 1
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .LBB0_4: # %for.body
; CHECK-NEXT:    # Parent Loop BB0_3 Depth=1
; CHECK-NEXT:    # => This Inner Loop Header: Depth=2
; CHECK-NEXT:    lwz.u $r5 = 0[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbfw $r4 = $r2, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    acswapw 0[$r12] = $r4r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cb.even $r4 ? .LBB0_4
; CHECK-NEXT:    ;;
; CHECK-NEXT:  # %bb.5: # %for.body
; CHECK-NEXT:    # in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    copyw $r2 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r2 = 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sw 0[$r0] = $r2
; CHECK-NEXT:    addd $r0 = $r0, 4
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .__LOOPDO_0_END_:
; CHECK-NEXT:  .LBB0_2: # %for.cond.cleanup
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %a = alloca i32, align 4
  %cmp8 = icmp eq i32 %num, 0
  br i1 %cmp8, label %for.cond.cleanup, label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %entry
  %0 = bitcast i32* %a to i8*
  %1 = zext i32 %num to i64
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %indvars.iv = phi i64 [ 0, %for.body.lr.ph ], [ %indvars.iv.next, %for.body ]
  %2 = trunc i64 %indvars.iv to i32
  store i32 %2, i32* %a, align 4
  %3 = atomicrmw sub i32* %a, i32 4 monotonic
  %arrayidx = getelementptr inbounds i32, i32* %x, i64 %indvars.iv
  store i32 16, i32* %arrayidx, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %cmp = icmp eq i64 %indvars.iv.next, %1
  br i1 %cmp, label %for.cond.cleanup, label %for.body
}

