; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -o - %s | FileCheck %s
target triple = "kvx-unknown-cos"

@tls = thread_local(localexec) global i32 0, align 4

define i32 @test() {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = @tlsle( tls )
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz $r0 = $r0[$r13]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load i32, i32* @tls, align 4
  ret i32 %0
}
