; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s | FileCheck %s
target triple = "kvx-kalray-cos"

define void @test_v1_select(<1 x i8> * %m, <1 x i8> * %n){
; CHECK-LABEL: test_v1_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbz $r2 = 0[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lbs $r1 = 0[$r1]
; CHECK-NEXT:    compw.eq $r3 = $r2, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compw.gt $r4 = $r1, -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andw $r3 = $r3, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r1 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sb 0[$r0] = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <1 x i8>, <1 x i8>* %m, align 8
  %v2 = load <1 x i8>, <1 x i8>* %n, align 8
  %c1 = icmp eq <1 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <1 x i8> %v2, <i8 -1>
  %c3 = and <1 x i1> %c1, %c2
  %v3 = select <1 x i1> %c3, <1 x i8> %v1, <1 x i8> %v2
  store <1 x i8> %v3, <1 x i8> * %m, align 8
  ret void
}

define void @test_v2_select(<2 x i8> * %m, <2 x i8> * %n){
; CHECK-LABEL: test_v2_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhz $r1 = 0[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lhz $r2 = 0[$r0]
; CHECK-NEXT:    extfz $r5 = $r1, 7, 0
; CHECK-NEXT:    extfz $r1 = $r1, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r3 = $r2, 7, 0
; CHECK-NEXT:    sxbd $r6 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r4 = $r3
; CHECK-NEXT:    copyw $r7 = $r6
; CHECK-NEXT:    make $r6 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r6 = 0
; CHECK-NEXT:    extfz $r2 = $r2, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r7 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r4 = $r7
; CHECK-NEXT:    zxbd $r6 = $r2
; CHECK-NEXT:    sxbd $r7 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r8 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r8 ? $r7 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r8 = $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r8 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r6 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r1 = $r2
; CHECK-NEXT:    cmoved.wnez $r4 ? $r5 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r5 = $r1, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sh 0[$r0] = $r5
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <2 x i8>, <2 x i8>* %m, align 8
  %v2 = load <2 x i8>, <2 x i8>* %n, align 8
  %c1 = icmp eq <2 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <2 x i8> %v2, <i8 -1, i8 -1>
  %c3 = and <2 x i1> %c1, %c2
  %v3 = select <2 x i1> %c3, <2 x i8> %v1, <2 x i8> %v2
  store <2 x i8> %v3, <2 x i8> * %m, align 8
  ret void
}

define void @test_v3_select(<3 x i8> * %m, <3 x i8> * %n){
; CHECK-LABEL: test_v3_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwz $r1 = 0[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz $r2 = 0[$r0]
; CHECK-NEXT:    extfz $r5 = $r1, 23, 16
; CHECK-NEXT:    extfz $r8 = $r1, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r6 = $r5
; CHECK-NEXT:    extfz $r3 = $r2, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r4 = $r3
; CHECK-NEXT:    copyw $r7 = $r6
; CHECK-NEXT:    make $r6 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r6 = 0
; CHECK-NEXT:    sxbd $r9 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r11 = $r1, 15, 8
; CHECK-NEXT:    copyd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r7 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r4 = $r7
; CHECK-NEXT:    extfz $r6 = $r2, 7, 0
; CHECK-NEXT:    copyw $r10 = $r9
; CHECK-NEXT:    make $r9 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r10 ? $r9 = 0
; CHECK-NEXT:    sxbd $r15 = $r11
; CHECK-NEXT:    zxbd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r16 = $r15
; CHECK-NEXT:    make $r15 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r16 ? $r15 = 0
; CHECK-NEXT:    extfz $r1 = $r1, 31, 24
; CHECK-NEXT:    copyd $r10 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r7 ? $r10 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r7 = $r10
; CHECK-NEXT:    extfz $r9 = $r2, 15, 8
; CHECK-NEXT:    extfz $r2 = $r2, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r10 = $r9
; CHECK-NEXT:    copyd $r16 = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r16 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r10 = $r16
; CHECK-NEXT:    sxbd $r15 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compw.gt $r15 = $r15, $r0
; CHECK-NEXT:    cmoved.wnez $r10 ? $r11 = $r9
; CHECK-NEXT:    cmoved.wnez $r7 ? $r8 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r5 = $r3
; CHECK-NEXT:    insf $r8 = $r11, 15, 8
; CHECK-NEXT:    copyw $r16 = $r15
; CHECK-NEXT:    make $r15 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.weqz $r16 ? $r15 = 0
; CHECK-NEXT:    insf $r8 = $r5, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r1 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r8 = $r1, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r8, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sb 2[$r0] = $r1
; CHECK-NEXT:    zxhd $r1 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sh 0[$r0] = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <3 x i8>, <3 x i8>* %m, align 8
  %v2 = load <3 x i8>, <3 x i8>* %n, align 8
  %c1 = icmp eq <3 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <3 x i8> %v2, <i8 -1, i8 -1, i8 -1>
  %c3 = and <3 x i1> %c1, %c2
  %v3 = select <3 x i1> %c3, <3 x i8> %v1, <3 x i8> %v2
  store <3 x i8> %v3, <3 x i8> * %m, align 8
  ret void
}

; TODO: Byte selects in 4xi8 can be done by a
; single sbmm8 or perhaps two CMOVEHQ after
; extending the i8 to a i16
define void @test_v4_select(<4 x i8> * %m, <4 x i8> * %n){
; CHECK-LABEL: test_v4_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwz $r1 = 0[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz $r2 = 0[$r0]
; CHECK-NEXT:    extfz $r5 = $r1, 31, 24
; CHECK-NEXT:    extfz $r8 = $r1, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r6 = $r5
; CHECK-NEXT:    extfz $r3 = $r2, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r4 = $r3
; CHECK-NEXT:    copyw $r7 = $r6
; CHECK-NEXT:    make $r6 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r6 = 0
; CHECK-NEXT:    sxbd $r9 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r11 = $r1, 7, 0
; CHECK-NEXT:    copyd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r7 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r4 = $r7
; CHECK-NEXT:    extfz $r6 = $r2, 23, 16
; CHECK-NEXT:    copyw $r10 = $r9
; CHECK-NEXT:    make $r9 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r10 ? $r9 = 0
; CHECK-NEXT:    sxbd $r15 = $r11
; CHECK-NEXT:    zxbd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r16 = $r15
; CHECK-NEXT:    make $r15 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r16 ? $r15 = 0
; CHECK-NEXT:    extfz $r1 = $r1, 15, 8
; CHECK-NEXT:    copyd $r10 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r7 ? $r10 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r7 = $r10
; CHECK-NEXT:    extfz $r9 = $r2, 7, 0
; CHECK-NEXT:    extfz $r2 = $r2, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r10 = $r9
; CHECK-NEXT:    copyd $r16 = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r16 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r10 = $r16
; CHECK-NEXT:    zxbd $r15 = $r2
; CHECK-NEXT:    sxbd $r16 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r17 = $r16
; CHECK-NEXT:    make $r16 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r17 ? $r16 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r17 = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r17 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r15 = $r17
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r1 = $r2
; CHECK-NEXT:    cmoved.wnez $r10 ? $r11 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r11 = $r1, 15, 8
; CHECK-NEXT:    cmoved.wnez $r7 ? $r8 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r5 = $r3
; CHECK-NEXT:    insf $r11 = $r8, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r11 = $r5, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sw 0[$r0] = $r11
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <4 x i8>, <4 x i8>* %m, align 8
  %v2 = load <4 x i8>, <4 x i8>* %n, align 8
  %c1 = icmp eq <4 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <4 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <4 x i1> %c1, %c2
  %v3 = select <4 x i1> %c3, <4 x i8> %v1, <4 x i8> %v2
  store <4 x i8> %v3, <4 x i8> * %m, align 8
  ret void
}

define void @test_v8_select(<8 x i8> * %m, <8 x i8> * %n){
; CHECK-LABEL: test_v8_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r1 = 0[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r2 = 0[$r0]
; CHECK-NEXT:    extfz $r6 = $r1, 63, 32
; CHECK-NEXT:    extfz $r1 = $r1, 31, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r3 = $r2, 63, 32
; CHECK-NEXT:    extfz $r7 = $r6, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r8 = $r7
; CHECK-NEXT:    extfz $r4 = $r3, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r10 = $r6, 23, 16
; CHECK-NEXT:    zxbd $r5 = $r4
; CHECK-NEXT:    copyw $r9 = $r8
; CHECK-NEXT:    make $r8 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r9 ? $r8 = 0
; CHECK-NEXT:    extfz $r16 = $r6, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r11 = $r10
; CHECK-NEXT:    copyd $r9 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r5 ? $r9 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r5 = $r9
; CHECK-NEXT:    extfz $r8 = $r3, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r9 = $r8
; CHECK-NEXT:    copyw $r15 = $r11
; CHECK-NEXT:    make $r11 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r15 ? $r11 = 0
; CHECK-NEXT:    sxbd $r17 = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r6 = $r6, 7, 0
; CHECK-NEXT:    copyd $r15 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r15 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r9 = $r15
; CHECK-NEXT:    extfz $r11 = $r3, 15, 8
; CHECK-NEXT:    copyw $r32 = $r17
; CHECK-NEXT:    make $r17 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r32 ? $r17 = 0
; CHECK-NEXT:    extfz $r3 = $r3, 7, 0
; CHECK-NEXT:    zxbd $r15 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r34 = $r1, 31, 24
; CHECK-NEXT:    extfz $r2 = $r2, 31, 0
; CHECK-NEXT:    copyd $r32 = $r17
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r32 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r15 = $r32
; CHECK-NEXT:    zxbd $r17 = $r3
; CHECK-NEXT:    sxbd $r35 = $r34
; CHECK-NEXT:    extfz $r37 = $r1, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r32 = $r6
; CHECK-NEXT:    copyw $r36 = $r35
; CHECK-NEXT:    make $r35 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r36 ? $r35 = 0
; CHECK-NEXT:    sxbd $r38 = $r37
; CHECK-NEXT:    copyw $r33 = $r32
; CHECK-NEXT:    make $r32 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r33 ? $r32 = 0
; CHECK-NEXT:    extfz $r40 = $r1, 7, 0
; CHECK-NEXT:    copyw $r39 = $r38
; CHECK-NEXT:    make $r38 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r39 ? $r38 = 0
; CHECK-NEXT:    extfz $r1 = $r1, 15, 8
; CHECK-NEXT:    copyd $r33 = $r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r17 ? $r33 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r17 = $r33
; CHECK-NEXT:    extfz $r32 = $r2, 31, 24
; CHECK-NEXT:    sxbd $r41 = $r40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r33 = $r32
; CHECK-NEXT:    copyw $r42 = $r41
; CHECK-NEXT:    make $r41 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r42 ? $r41 = 0
; CHECK-NEXT:    copyd $r36 = $r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r33 ? $r36 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r33 = $r36
; CHECK-NEXT:    extfz $r35 = $r2, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r36 = $r35
; CHECK-NEXT:    copyd $r39 = $r38
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r36 ? $r39 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r36 = $r39
; CHECK-NEXT:    extfz $r38 = $r2, 7, 0
; CHECK-NEXT:    extfz $r2 = $r2, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r39 = $r38
; CHECK-NEXT:    copyd $r42 = $r41
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r39 ? $r42 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r39 = $r42
; CHECK-NEXT:    zxbd $r41 = $r2
; CHECK-NEXT:    sxbd $r42 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r43 = $r42
; CHECK-NEXT:    make $r42 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r43 ? $r42 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r43 = $r42
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r41 ? $r43 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r41 = $r43
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r41 ? $r1 = $r2
; CHECK-NEXT:    cmoved.wnez $r39 ? $r40 = $r38
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r1, 15, 8
; CHECK-NEXT:    cmoved.wnez $r36 ? $r37 = $r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r33 ? $r34 = $r32
; CHECK-NEXT:    cmoved.wnez $r17 ? $r6 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r16 = $r11
; CHECK-NEXT:    cmoved.wnez $r9 ? $r10 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r5 ? $r7 = $r4
; CHECK-NEXT:    insf $r40 = $r37, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r34, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r6, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r16, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r10, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r7, 63, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 0[$r0] = $r40
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <8 x i8>, <8 x i8>* %m, align 8
  %v2 = load <8 x i8>, <8 x i8>* %n, align 8
  %c1 = icmp eq <8 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <8 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <8 x i1> %c1, %c2
  %v3 = select <8 x i1> %c3, <8 x i8> %v1, <8 x i8> %v2
  store <8 x i8> %v3, <8 x i8> * %m, align 8
  ret void
}

define void @test_v16_select(<16 x i8> * %m, <16 x i8> * %n){
; CHECK-LABEL: test_v16_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r8 = 8[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r35 = 0[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r37 = 8[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r33 = 0[$r0]
; CHECK-NEXT:    extfz $r1 = $r8, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r2 = $r1
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r2 ? $r3 = 0
; CHECK-NEXT:    extfz $r2 = $r8, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r4 = $r2
; CHECK-NEXT:    make $r36 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r36 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r3, 15, 8
; CHECK-NEXT:    extfz $r3 = $r8, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r4 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r5 = $r4
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r5 ? $r4 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r4, 23, 16
; CHECK-NEXT:    extfz $r4 = $r8, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r5 = $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r6 = $r5
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r5 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r5, 31, 24
; CHECK-NEXT:    extfz $r5 = $r8, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r6 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r7 = $r6
; CHECK-NEXT:    make $r6 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r7 ? $r6 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r6, 39, 32
; CHECK-NEXT:    extfz $r6 = $r8, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r9 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r7 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r7, 47, 40
; CHECK-NEXT:    extfz $r7 = $r8, 55, 48
; CHECK-NEXT:    srld $r8 = $r8, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r9 = $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r10 = $r9
; CHECK-NEXT:    make $r9 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r9 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r9, 55, 48
; CHECK-NEXT:    zxbd $r9 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r10 = $r9
; CHECK-NEXT:    make $r9 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r9 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r9, 63, 56
; CHECK-NEXT:    extfz $r9 = $r33, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r10 = $r9
; CHECK-NEXT:    make $r11 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r11 = 0
; CHECK-NEXT:    extfz $r10 = $r33, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r15 = $r10
; CHECK-NEXT:    make $r38 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r38 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r11, 15, 8
; CHECK-NEXT:    extfz $r11 = $r33, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r15 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r16 = $r15
; CHECK-NEXT:    make $r15 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r16 ? $r15 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r15, 23, 16
; CHECK-NEXT:    extfz $r15 = $r33, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r16 = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r17 = $r16
; CHECK-NEXT:    make $r16 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r17 ? $r16 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r16, 31, 24
; CHECK-NEXT:    extfz $r16 = $r33, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r17 = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r32 = $r17
; CHECK-NEXT:    make $r17 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r17 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r17, 39, 32
; CHECK-NEXT:    extfz $r17 = $r33, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r32 = $r17
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r34 = $r32
; CHECK-NEXT:    make $r32 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r34 ? $r32 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r32, 47, 40
; CHECK-NEXT:    extfz $r32 = $r33, 55, 48
; CHECK-NEXT:    srld $r33 = $r33, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r34 = $r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r39 = $r34
; CHECK-NEXT:    make $r34 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r39 ? $r34 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r34, 55, 48
; CHECK-NEXT:    zxbd $r34 = $r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r39 = $r34
; CHECK-NEXT:    make $r34 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r39 ? $r34 = 0
; CHECK-NEXT:    extfz $r39 = $r37, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r34, 63, 56
; CHECK-NEXT:    sxbd $r34 = $r39
; CHECK-NEXT:    make $r40 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r34 ? $r40 = 0
; CHECK-NEXT:    extfz $r34 = $r37, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r41 = $r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r42 = $r41
; CHECK-NEXT:    make $r41 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r42 ? $r41 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r40, 15, 8
; CHECK-NEXT:    extfz $r40 = $r37, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r42 = $r40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r43 = $r42
; CHECK-NEXT:    make $r42 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r43 ? $r42 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r42, 23, 16
; CHECK-NEXT:    extfz $r42 = $r37, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r43 = $r42
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r44 = $r43
; CHECK-NEXT:    make $r43 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r44 ? $r43 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r43, 31, 24
; CHECK-NEXT:    extfz $r43 = $r37, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r44 = $r43
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r45 = $r44
; CHECK-NEXT:    make $r44 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r45 ? $r44 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r44, 39, 32
; CHECK-NEXT:    extfz $r44 = $r37, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r45 = $r44
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r46 = $r45
; CHECK-NEXT:    make $r45 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r46 ? $r45 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r45, 47, 40
; CHECK-NEXT:    extfz $r45 = $r37, 55, 48
; CHECK-NEXT:    srld $r37 = $r37, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r46 = $r45
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r47 = $r46
; CHECK-NEXT:    make $r46 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r47 ? $r46 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r46, 55, 48
; CHECK-NEXT:    sxbd $r46 = $r37
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r47 = $r46
; CHECK-NEXT:    make $r46 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r47 ? $r46 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r46, 63, 56
; CHECK-NEXT:    extfz $r46 = $r35, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r47 = $r46
; CHECK-NEXT:    andd $r36 = $r36, $r41
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r48 = $r47
; CHECK-NEXT:    make $r47 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r48 ? $r47 = 0
; CHECK-NEXT:    extfz $r41 = $r36, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r48 = $r35, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r49 = $r48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r50 = $r49
; CHECK-NEXT:    make $r49 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r50 ? $r49 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r47, 15, 8
; CHECK-NEXT:    extfz $r47 = $r35, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r50 = $r47
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r51 = $r50
; CHECK-NEXT:    make $r50 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r51 ? $r50 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r50, 23, 16
; CHECK-NEXT:    extfz $r50 = $r35, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r51 = $r50
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r52 = $r51
; CHECK-NEXT:    make $r51 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r52 ? $r51 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r51, 31, 24
; CHECK-NEXT:    extfz $r51 = $r35, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r52 = $r51
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r53 = $r52
; CHECK-NEXT:    make $r52 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r53 ? $r52 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r52, 39, 32
; CHECK-NEXT:    extfz $r52 = $r35, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r53 = $r52
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r54 = $r53
; CHECK-NEXT:    make $r53 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r54 ? $r53 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r53, 47, 40
; CHECK-NEXT:    extfz $r53 = $r35, 55, 48
; CHECK-NEXT:    srld $r35 = $r35, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r54 = $r53
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r55 = $r54
; CHECK-NEXT:    make $r54 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r55 ? $r54 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r54, 55, 48
; CHECK-NEXT:    sxbd $r54 = $r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r55 = $r54
; CHECK-NEXT:    make $r54 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r55 ? $r54 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r54, 63, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r38 = $r38, $r49
; CHECK-NEXT:    cmoved.wnez $r41 ? $r39 = $r1
; CHECK-NEXT:    extfz $r1 = $r36, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r34 = $r2
; CHECK-NEXT:    extfz $r1 = $r36, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r40 = $r3
; CHECK-NEXT:    extfz $r1 = $r36, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r34 = $r39, 15, 8
; CHECK-NEXT:    cmoved.wnez $r1 ? $r42 = $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r36, 39, 32
; CHECK-NEXT:    insf $r34 = $r40, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r43 = $r5
; CHECK-NEXT:    extfz $r1 = $r36, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r34 = $r42, 31, 24
; CHECK-NEXT:    cmoved.wnez $r1 ? $r44 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r36, 55, 48
; CHECK-NEXT:    insf $r34 = $r43, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r45 = $r7
; CHECK-NEXT:    srld $r1 = $r36, 56
; CHECK-NEXT:    insf $r34 = $r44, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r37 = $r8
; CHECK-NEXT:    extfz $r1 = $r38, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r34 = $r45, 55, 48
; CHECK-NEXT:    cmoved.wnez $r1 ? $r46 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r38, 7, 0
; CHECK-NEXT:    insf $r34 = $r37, 63, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r48 = $r10
; CHECK-NEXT:    extfz $r1 = $r38, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r47 = $r11
; CHECK-NEXT:    insf $r48 = $r46, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r38, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r50 = $r15
; CHECK-NEXT:    insf $r48 = $r47, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r38, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r51 = $r16
; CHECK-NEXT:    insf $r48 = $r50, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r38, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r52 = $r17
; CHECK-NEXT:    insf $r48 = $r51, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r38, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r1 ? $r53 = $r32
; CHECK-NEXT:    insf $r48 = $r52, 47, 40
; CHECK-NEXT:    srld $r1 = $r38, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r48 = $r53, 55, 48
; CHECK-NEXT:    cmoved.wnez $r1 ? $r35 = $r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r48 = $r35, 63, 56
; CHECK-NEXT:    sd 8[$r0] = $r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 0[$r0] = $r48
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <16 x i8>, <16 x i8>* %m, align 16
  %v2 = load <16 x i8>, <16 x i8>* %n, align 16
  %c1 = icmp eq <16 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <16 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <16 x i1> %c1, %c2
  %v3 = select <16 x i1> %c3, <16 x i8> %v1, <16 x i8> %v2
  store <16 x i8> %v3, <16 x i8> * %m, align 16
  ret void
}

define void @test_v32_select(<32 x i8> * %m, <32 x i8> * %n){
; CHECK-LABEL: test_v32_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -128
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa_offset 128
; CHECK-NEXT:    so 80[$r12] = $r28r29r30r31
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 31, -24
; CHECK-NEXT:    .cfi_offset 30, -32
; CHECK-NEXT:    .cfi_offset 29, -40
; CHECK-NEXT:    .cfi_offset 28, -48
; CHECK-NEXT:    so 48[$r12] = $r24r25r26r27
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 27, -56
; CHECK-NEXT:    .cfi_offset 26, -64
; CHECK-NEXT:    .cfi_offset 25, -72
; CHECK-NEXT:    .cfi_offset 24, -80
; CHECK-NEXT:    so 16[$r12] = $r20r21r22r23
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 23, -88
; CHECK-NEXT:    .cfi_offset 22, -96
; CHECK-NEXT:    .cfi_offset 21, -104
; CHECK-NEXT:    .cfi_offset 20, -112
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 19, -120
; CHECK-NEXT:    .cfi_offset 18, -128
; CHECK-NEXT:    ld $r11 = 8[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r2 = 16[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r3 = 24[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r25 = 0[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r63 = 8[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r52 = 16[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r44 = 24[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r36 = 0[$r0]
; CHECK-NEXT:    extfz $r4 = $r11, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r1 = $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r5 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r5 ? $r1 = 0
; CHECK-NEXT:    extfz $r5 = $r11, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r6 = $r5
; CHECK-NEXT:    make $r55 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r55 = 0
; CHECK-NEXT:    extfz $r6 = $r11, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 15, 8
; CHECK-NEXT:    zxbd $r1 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r7 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r7 ? $r1 = 0
; CHECK-NEXT:    extfz $r7 = $r11, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 23, 16
; CHECK-NEXT:    zxbd $r1 = $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r8 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r1 = 0
; CHECK-NEXT:    extfz $r8 = $r11, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 31, 24
; CHECK-NEXT:    zxbd $r1 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r9 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r1 = 0
; CHECK-NEXT:    extfz $r9 = $r11, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 39, 32
; CHECK-NEXT:    zxbd $r1 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r10 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r1 = 0
; CHECK-NEXT:    extfz $r10 = $r11, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 47, 40
; CHECK-NEXT:    srld $r11 = $r11, 56
; CHECK-NEXT:    zxbd $r1 = $r10
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r15 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r1 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 55, 48
; CHECK-NEXT:    zxbd $r1 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r15 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r1 = 0
; CHECK-NEXT:    extfz $r15 = $r36, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 63, 56
; CHECK-NEXT:    zxbd $r1 = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r16 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r16 ? $r1 = 0
; CHECK-NEXT:    extfz $r16 = $r36, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r17 = $r16
; CHECK-NEXT:    make $r56 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r17 ? $r56 = 0
; CHECK-NEXT:    extfz $r17 = $r36, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r56 = $r1, 15, 8
; CHECK-NEXT:    zxbd $r1 = $r17
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r32 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r1 = 0
; CHECK-NEXT:    extfz $r32 = $r36, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r56 = $r1, 23, 16
; CHECK-NEXT:    zxbd $r1 = $r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r33 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r33 ? $r1 = 0
; CHECK-NEXT:    extfz $r33 = $r36, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r56 = $r1, 31, 24
; CHECK-NEXT:    zxbd $r1 = $r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r34 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r34 ? $r1 = 0
; CHECK-NEXT:    extfz $r34 = $r36, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r56 = $r1, 39, 32
; CHECK-NEXT:    zxbd $r1 = $r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r35 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r35 ? $r1 = 0
; CHECK-NEXT:    extfz $r35 = $r36, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r56 = $r1, 47, 40
; CHECK-NEXT:    srld $r36 = $r36, 56
; CHECK-NEXT:    zxbd $r1 = $r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r37 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r37 ? $r1 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r56 = $r1, 55, 48
; CHECK-NEXT:    zxbd $r1 = $r36
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r37 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r37 ? $r1 = 0
; CHECK-NEXT:    extfz $r37 = $r44, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r56 = $r1, 63, 56
; CHECK-NEXT:    zxbd $r1 = $r37
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r38 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r38 ? $r1 = 0
; CHECK-NEXT:    extfz $r38 = $r44, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r39 = $r38
; CHECK-NEXT:    make $r54 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r39 ? $r54 = 0
; CHECK-NEXT:    extfz $r39 = $r44, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r1, 15, 8
; CHECK-NEXT:    zxbd $r1 = $r39
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r40 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r40 ? $r1 = 0
; CHECK-NEXT:    extfz $r40 = $r44, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r1, 23, 16
; CHECK-NEXT:    zxbd $r1 = $r40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r41 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r41 ? $r1 = 0
; CHECK-NEXT:    extfz $r41 = $r44, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r1, 31, 24
; CHECK-NEXT:    zxbd $r1 = $r41
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r42 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r42 ? $r1 = 0
; CHECK-NEXT:    extfz $r42 = $r44, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r1, 39, 32
; CHECK-NEXT:    zxbd $r1 = $r42
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r43 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r43 ? $r1 = 0
; CHECK-NEXT:    extfz $r43 = $r44, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r1, 47, 40
; CHECK-NEXT:    srld $r44 = $r44, 56
; CHECK-NEXT:    zxbd $r1 = $r43
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r45 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r45 ? $r1 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r1, 55, 48
; CHECK-NEXT:    zxbd $r1 = $r44
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r45 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r45 ? $r1 = 0
; CHECK-NEXT:    extfz $r45 = $r52, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r1, 63, 56
; CHECK-NEXT:    zxbd $r1 = $r45
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r46 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r46 ? $r1 = 0
; CHECK-NEXT:    extfz $r46 = $r52, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r47 = $r46
; CHECK-NEXT:    make $r57 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r47 ? $r57 = 0
; CHECK-NEXT:    extfz $r47 = $r52, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r1, 15, 8
; CHECK-NEXT:    zxbd $r1 = $r47
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r48 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r48 ? $r1 = 0
; CHECK-NEXT:    extfz $r48 = $r52, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r1, 23, 16
; CHECK-NEXT:    zxbd $r1 = $r48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r49 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r49 ? $r1 = 0
; CHECK-NEXT:    extfz $r49 = $r52, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r1, 31, 24
; CHECK-NEXT:    zxbd $r1 = $r49
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r50 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r50 ? $r1 = 0
; CHECK-NEXT:    extfz $r50 = $r52, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r1, 39, 32
; CHECK-NEXT:    zxbd $r1 = $r50
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r51 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r51 ? $r1 = 0
; CHECK-NEXT:    extfz $r51 = $r52, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r1, 47, 40
; CHECK-NEXT:    srld $r52 = $r52, 56
; CHECK-NEXT:    zxbd $r1 = $r51
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r53 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r53 ? $r1 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r1, 55, 48
; CHECK-NEXT:    zxbd $r1 = $r52
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r53 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r53 ? $r1 = 0
; CHECK-NEXT:    extfz $r53 = $r63, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r1, 63, 56
; CHECK-NEXT:    sxbd $r1 = $r53
; CHECK-NEXT:    make $r58 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r1 ? $r58 = 0
; CHECK-NEXT:    extfz $r1 = $r63, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r59 = $r1
; CHECK-NEXT:    make $r28 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r59 ? $r28 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r58, 15, 8
; CHECK-NEXT:    extfz $r58 = $r63, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r59 = $r58
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r60 = $r59
; CHECK-NEXT:    make $r59 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r60 ? $r59 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r59, 23, 16
; CHECK-NEXT:    extfz $r59 = $r63, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r60 = $r59
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r61 = $r60
; CHECK-NEXT:    make $r60 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r61 ? $r60 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r60, 31, 24
; CHECK-NEXT:    extfz $r60 = $r63, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r61 = $r60
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r62 = $r61
; CHECK-NEXT:    make $r61 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r62 ? $r61 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r61, 39, 32
; CHECK-NEXT:    extfz $r61 = $r63, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r62 = $r61
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r18 = $r62
; CHECK-NEXT:    make $r62 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r18 ? $r62 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r62, 47, 40
; CHECK-NEXT:    extfz $r62 = $r63, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r18 = $r62
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r19 = $r18
; CHECK-NEXT:    make $r18 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r19 ? $r18 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r18, 55, 48
; CHECK-NEXT:    srld $r18 = $r63, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r63 = $r18
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r19 = $r63
; CHECK-NEXT:    make $r63 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r19 ? $r63 = 0
; CHECK-NEXT:    extfz $r19 = $r25, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r63, 63, 56
; CHECK-NEXT:    sxbd $r63 = $r19
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r55 = $r55, $r28
; CHECK-NEXT:    make $r20 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r63 ? $r20 = 0
; CHECK-NEXT:    extfz $r63 = $r25, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r28 = $r55, 15, 8
; CHECK-NEXT:    sxbd $r21 = $r63
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r28 ? $r53 = $r4
; CHECK-NEXT:    make $r29 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r21 ? $r29 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r29 = $r20, 15, 8
; CHECK-NEXT:    extfz $r20 = $r25, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r21 = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r22 = $r21
; CHECK-NEXT:    make $r21 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r22 ? $r21 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r29 = $r21, 23, 16
; CHECK-NEXT:    extfz $r21 = $r25, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r22 = $r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r23 = $r22
; CHECK-NEXT:    make $r22 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r23 ? $r22 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r29 = $r22, 31, 24
; CHECK-NEXT:    extfz $r22 = $r25, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r23 = $r22
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r24 = $r23
; CHECK-NEXT:    make $r23 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r24 ? $r23 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r29 = $r23, 39, 32
; CHECK-NEXT:    extfz $r23 = $r25, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r24 = $r23
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r26 = $r24
; CHECK-NEXT:    make $r24 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r26 ? $r24 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r29 = $r24, 47, 40
; CHECK-NEXT:    extfz $r24 = $r25, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r26 = $r24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r27 = $r26
; CHECK-NEXT:    make $r26 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r27 ? $r26 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r29 = $r26, 55, 48
; CHECK-NEXT:    srld $r26 = $r25, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r25 = $r26
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r27 = $r25
; CHECK-NEXT:    make $r25 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r27 ? $r25 = 0
; CHECK-NEXT:    extfz $r27 = $r3, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r29 = $r25, 63, 56
; CHECK-NEXT:    sxbd $r25 = $r27
; CHECK-NEXT:    make $r30 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r25 ? $r30 = 0
; CHECK-NEXT:    extfz $r25 = $r3, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r4 = $r25
; CHECK-NEXT:    make $r31 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r4 ? $r31 = 0
; CHECK-NEXT:    extfz $r4 = $r55, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r1 = $r5
; CHECK-NEXT:    extfz $r5 = $r55, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r4 = $r3, 23, 16
; CHECK-NEXT:    cmoved.wnez $r5 ? $r58 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r5 = $r4
; CHECK-NEXT:    insf $r31 = $r30, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r6 = $r5
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r6 ? $r5 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r31 = $r5, 23, 16
; CHECK-NEXT:    extfz $r5 = $r55, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r5 ? $r59 = $r7
; CHECK-NEXT:    extfz $r5 = $r3, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r6 = $r55, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r60 = $r8
; CHECK-NEXT:    sxbd $r6 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r7 = $r6
; CHECK-NEXT:    make $r6 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r6 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r31 = $r6, 31, 24
; CHECK-NEXT:    extfz $r6 = $r55, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r61 = $r9
; CHECK-NEXT:    extfz $r6 = $r3, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r7 = $r55, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r7 ? $r62 = $r10
; CHECK-NEXT:    sxbd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r8 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r8 ? $r7 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r31 = $r7, 39, 32
; CHECK-NEXT:    srld $r8 = $r55, 56
; CHECK-NEXT:    extfz $r7 = $r3, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r18 = $r11
; CHECK-NEXT:    sxbd $r8 = $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r9 = $r8
; CHECK-NEXT:    make $r8 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r9 ? $r8 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r31 = $r8, 47, 40
; CHECK-NEXT:    andd $r8 = $r56, $r29
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r9 = $r8, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r19 = $r15
; CHECK-NEXT:    extfz $r9 = $r3, 55, 48
; CHECK-NEXT:    srld $r3 = $r3, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r10 = $r8, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r63 = $r16
; CHECK-NEXT:    sxbd $r10 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r11 = $r10
; CHECK-NEXT:    make $r10 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r11 ? $r10 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r31 = $r10, 55, 48
; CHECK-NEXT:    extfz $r10 = $r8, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r20 = $r17
; CHECK-NEXT:    sxbd $r10 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r11 = $r10
; CHECK-NEXT:    make $r10 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r11 ? $r10 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r31 = $r10, 63, 56
; CHECK-NEXT:    extfz $r10 = $r8, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r21 = $r32
; CHECK-NEXT:    extfz $r10 = $r2, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r11 = $r8, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r11 ? $r22 = $r33
; CHECK-NEXT:    sxbd $r11 = $r10
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r15 = $r11
; CHECK-NEXT:    make $r11 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r15 ? $r11 = 0
; CHECK-NEXT:    extfz $r15 = $r8, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r23 = $r34
; CHECK-NEXT:    extfz $r15 = $r2, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r16 = $r8, 55, 48
; CHECK-NEXT:    srld $r8 = $r8, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r16 ? $r24 = $r35
; CHECK-NEXT:    sxbd $r16 = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r26 = $r36
; CHECK-NEXT:    copyw $r17 = $r16
; CHECK-NEXT:    make $r16 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r17 ? $r16 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r16 = $r11, 15, 8
; CHECK-NEXT:    extfz $r11 = $r2, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r8 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r17 = $r8
; CHECK-NEXT:    make $r8 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r17 ? $r8 = 0
; CHECK-NEXT:    andd $r17 = $r54, $r31
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r16 = $r8, 23, 16
; CHECK-NEXT:    extfz $r8 = $r2, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r32 = $r17, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r27 = $r37
; CHECK-NEXT:    sxbd $r32 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r33 = $r32
; CHECK-NEXT:    make $r32 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r33 ? $r32 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r16 = $r32, 31, 24
; CHECK-NEXT:    extfz $r32 = $r17, 7, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r25 = $r38
; CHECK-NEXT:    extfz $r32 = $r2, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r33 = $r17, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r33 ? $r4 = $r39
; CHECK-NEXT:    sxbd $r33 = $r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r34 = $r33
; CHECK-NEXT:    make $r33 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r34 ? $r33 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r16 = $r33, 39, 32
; CHECK-NEXT:    extfz $r33 = $r17, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r33 ? $r5 = $r40
; CHECK-NEXT:    extfz $r33 = $r2, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r34 = $r17, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r34 ? $r6 = $r41
; CHECK-NEXT:    sxbd $r34 = $r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r35 = $r34
; CHECK-NEXT:    make $r34 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r35 ? $r34 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r16 = $r34, 47, 40
; CHECK-NEXT:    extfz $r34 = $r17, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r34 ? $r7 = $r42
; CHECK-NEXT:    extfz $r34 = $r2, 55, 48
; CHECK-NEXT:    srld $r2 = $r2, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r35 = $r17, 55, 48
; CHECK-NEXT:    srld $r17 = $r17, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r35 ? $r9 = $r43
; CHECK-NEXT:    sxbd $r35 = $r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r36 = $r35
; CHECK-NEXT:    make $r35 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r36 ? $r35 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r16 = $r35, 55, 48
; CHECK-NEXT:    cmoved.wnez $r17 ? $r3 = $r44
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r17 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r35 = $r17
; CHECK-NEXT:    make $r17 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r35 ? $r17 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r16 = $r17, 63, 56
; CHECK-NEXT:    insf $r1 = $r53, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r58, 23, 16
; CHECK-NEXT:    andd $r16 = $r57, $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r59, 31, 24
; CHECK-NEXT:    extfz $r17 = $r16, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r60, 39, 32
; CHECK-NEXT:    cmoved.wnez $r17 ? $r10 = $r45
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r17 = $r16, 7, 0
; CHECK-NEXT:    insf $r1 = $r61, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r17 ? $r15 = $r46
; CHECK-NEXT:    extfz $r17 = $r16, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r62, 55, 48
; CHECK-NEXT:    cmoved.wnez $r17 ? $r11 = $r47
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r17 = $r16, 31, 24
; CHECK-NEXT:    insf $r1 = $r18, 63, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r63 = $r19, 15, 8
; CHECK-NEXT:    cmoved.wnez $r17 ? $r8 = $r48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r63 = $r20, 23, 16
; CHECK-NEXT:    extfz $r17 = $r16, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r63 = $r21, 31, 24
; CHECK-NEXT:    cmoved.wnez $r17 ? $r32 = $r49
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r17 = $r16, 47, 40
; CHECK-NEXT:    insf $r63 = $r22, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r17 ? $r33 = $r50
; CHECK-NEXT:    extfz $r17 = $r16, 55, 48
; CHECK-NEXT:    srld $r16 = $r16, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r63 = $r23, 47, 40
; CHECK-NEXT:    cmoved.wnez $r17 ? $r34 = $r51
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r16 ? $r2 = $r52
; CHECK-NEXT:    insf $r63 = $r24, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r63 = $r26, 63, 56
; CHECK-NEXT:    insf $r25 = $r27, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r25 = $r4, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r25 = $r5, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r25 = $r6, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r25 = $r7, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r25 = $r9, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r25 = $r3, 63, 56
; CHECK-NEXT:    insf $r15 = $r10, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r15 = $r11, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r15 = $r8, 31, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r15 = $r32, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r15 = $r33, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r15 = $r34, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r15 = $r2, 63, 56
; CHECK-NEXT:    sd 24[$r0] = $r25
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 0[$r0] = $r63
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 8[$r0] = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r0] = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r20r21r22r23 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r24r25r26r27 = 48[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r28r29r30r31 = 80[$r12]
; CHECK-NEXT:    addd $r12 = $r12, 128
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <32 x i8>, <32 x i8>* %m, align 32
  %v2 = load <32 x i8>, <32 x i8>* %n, align 32
  %c1 = icmp eq <32 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <32 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <32 x i1> %c1, %c2
  %v3 = select <32 x i1> %c3, <32 x i8> %v1, <32 x i8> %v2
  store <32 x i8> %v3, <32 x i8> * %m, align 32
  ret void
}
