// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm -O3 -o - %s | FileCheck %s

// CHECK-LABEL: @test_vector(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, i8* [[PTR1:%.*]], i64 64
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[ADD_PTR]] to <256 x i1>*
// CHECK-NEXT:    [[TMP1:%.*]] = load <256 x i1>, <256 x i1>* [[TMP0]], align 32, !tbaa !2
// CHECK-NEXT:    [[ADD_PTR1:%.*]] = getelementptr inbounds i8, i8* [[PTR2:%.*]], i64 32
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i8* [[ADD_PTR1]] to <256 x i1>*
// CHECK-NEXT:    store <256 x i1> [[TMP1]], <256 x i1>* [[TMP2]], align 32, !tbaa !2
// CHECK-NEXT:    ret void
//
void test_vector(void *ptr1, void *ptr2) {
  __tca256 *inp = (__tca256 *)ptr1;
  __tca256 *outp = (__tca256 *)ptr2;
  *(outp + 1) = *(inp + 2);
}
